-- 1. Create the new sale_items table
create table if not exists sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references sales(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  quantity integer not null,
  unit_price numeric not null,
  total_price numeric not null,
  created_at timestamptz default now()
);

-- 2. Remove the old 'items' column from the sales table
alter table sales drop column if exists items;

-- 3. Add new columns to the sales table that were missing
alter table sales add column if not exists sale_number text;
alter table sales add column if not exists operator text;
alter table sales add column if not exists status text;

-- 4. Add new columns to the stock_movements table that were missing
alter table stock_movements add column if not exists previous_stock integer;
alter table stock_movements add column if not exists new_stock integer;
