-- Run this SQL in your Supabase SQL Editor to create the tables

-- Create products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  barcode text,
  sku text,
  category text,
  unit_type text,
  cost_price numeric,
  sale_price numeric,
  stock_quantity numeric default 0,
  min_stock integer default 5,
  is_active boolean default true,
  image_url text,
  created_at timestamptz default now()
);

-- Create sales table
create table if not exists sales (
  id bigint generated by default as identity primary key,
  total numeric,
  payment_method text,
  amount_paid numeric,
  change numeric,
  discount numeric,
  subtotal numeric,
  items jsonb,
  created_date timestamptz default now()
);

-- Create stock_movements table
create table if not exists stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id),
  product_name text,
  movement_type text,
  quantity numeric,
  previous_stock numeric,
  new_stock numeric,
  reason text,
  reference text,
  location text,
  created_date timestamptz default now()
);

-- Create store_settings table
create table if not exists store_settings (
  id bigint generated by default as identity primary key,
  store_name text,
  cnpj text,
  address text,
  phone text,
  printer_name text,
  printer_width integer,
  auto_print boolean default true,
  logo_url text,
  alert_email text,
  enable_stock_alerts boolean default true,
  alert_threshold integer default 10,
  created_at timestamptz default now()
);

-- Insert default settings if empty
insert into store_settings (store_name, auto_print, enable_stock_alerts, alert_threshold)
select 'Nexus Commerce', true, true, 10
where not exists (select 1 from store_settings);
